
using JetBrains.Annotations;
using System;
using UnityEngine;


namespace HutongGames.PlayMaker.Actions.Audio
{
	
	
	[System.Serializable]
	[PublicAPI]
	[ActionCategory(Category.AudioSource)]
	[ActionDescription("When set global effects on the AudioListener will not be applied to the audio sig" +
		"nal generated by the AudioSource. Does not apply if the AudioSource is playing i" +
		"nto a mixer group.")]
	[HelpURL("https://docs.unity3d.com/ScriptReference/AudioSource-bypassListenerEffects.html")]
	public sealed class AudioSourceSetBypassListenerEffects : BaseAction
	{
		
		[Tooltip("The AudioSource")]
		[SerializeField]
		private AudioSourceVar _audioSource;
		
		[Tooltip("Set AudioSource Bypass Listener Effects")]
		[SerializeField]
		private BoolVar _setBypassListenerEffects;
		
		public override bool CanExecute()
		{
			return CheckParameters(_audioSource, _setBypassListenerEffects);
		}
		
		public override void Execute()
		{
			_audioSource.Value.bypassListenerEffects = _setBypassListenerEffects.Value;
		}
		
		public override string GetSummary()
		{
			return "Set {_audioSource} bypass listener effects to {_setBypassListenerEffects}";
		}
	}
}
