
using JetBrains.Annotations;
using UnityEngine;


namespace HutongGames.PlayMaker.Actions
{
	
	
	[System.Serializable]
	[PublicAPI]
	[ActionCategory(Category.Collision)]
	[ActionDescription("The contact points generated by the physics engine. You should avoid using this a" +
		"s it produces memory garbage. Use GetContact or GetContacts instead.")]
	[HelpURL("https://docs.unity3d.com/ScriptReference/Collision-contacts.html")]
	public sealed class CollisionGetContacts : BaseAction
	{
		
		[Tooltip("The Collision")]
		[SerializeField]
		private CollisionRef _collision;
		
		[Tooltip("Get Collision Contacts")]
		[SerializeField]
		[WriteOnly]
		private ContactPointListRef _getContacts;
		
		public override bool CanExecute()
		{
			return CheckParameters(_collision, _getContacts);
		}
		
		public override void Execute()
		{
			_getContacts.Values = _collision.Value.contacts;
		}
		
		public override string GetSummary() => "Get {_collision} contacts -> {_getContacts}";
	}
}
