
using JetBrains.Annotations;
using System;
using UnityEngine;


namespace HutongGames.PlayMaker.Actions.UI
{
	
	
	[System.Serializable]
	[PublicAPI]
	[ActionCategory(Category.UGUI_Image)]
	[ActionDescription("Whether the UI Image should be displayed using the mesh generated by the TextureImporter, or by a simple quad mesh. ")]
	[HelpURL("https://docs.unity3d.com/Packages/com.unity.ugui@2.0/manual/script-Image.html")]
	public sealed class ImageSetUseSpriteMesh : BaseAction
	{
		
		[Tooltip("The Image")]
		[SerializeField]
		private ImageVar _image;
		
		[Tooltip("Set Image Use Sprite Mesh")]
		[SerializeField]
		private BoolVar _setUseSpriteMesh;
		
		public override bool CanExecute()
		{
			return CheckParameters(_image, _setUseSpriteMesh);
		}
		
		public override void Execute()
		{
			_image.Value.useSpriteMesh = _setUseSpriteMesh.Value;
		}
		
		public override string GetSummary()
		{
			return "Set {_image} use sprite mesh to {_setUseSpriteMesh}";
		}
	}
}
